### ISSUE TITLE
So no standalone app it`s intended for selfhost service?

### ISSUE THREAD

**Issue by necros2k7** [AivanF/ID-Detective-public#1]
subj

**Comment by AivanF** [comment]
Hi necros2k7!
1. The project was closed a while ago because of many reasons, so no updates will ever come.
2. The DB was huge, contained many GBs of indexed faces from Vk, and it had to be updated periodically. After closing the project, I deleted the DB without any come.
3. But, there is no technical reason why you cannot do all the work using the code to build a fresh DB and run it anywhere you want. You will only need a lot of computational resources and patience 😁 And probably a lawer, cuz nowadays Russian laws prohibit automatic usage of websites and social networks personal data, e.g such faces parsing.
